### PR TITLE
[Fix]: replace invalid or empty serial id with newly generated valid one

### LINKED ISSUE #321: CycloneDX `serialNumber` Not Assigned UUID When Empty or Invalid
## Description

When converting an SPDX SBOM to CycloneDX using protobom@v0.5.1 (e.g., with sbom-convert), the `serialNumber` in the output isn’t always set properly. If the original SBOM doesn’t have a valid unique identifier or  empty, the converted CycloneDX file fails validation in Dependency-Track v4.12.5 because it expects a specific format (urn:uuid:...).

#### To Reproduce
- Convert an SPDX SBOM with no unique identifier to CycloneDX using sbom-convert.
- Upload the result to Dependency-Track.
- It fails with an error about serialNumber not matching the required format.

#### Expected Behavior
- The serialNumber should always be a valid unique identifier (like urn:uuid:...) in the CycloneDX output, even if the input SBOM doesn’t provide one.

### PR DESCRIPTION
**Pull request by viveksahu26**
closes #321 

This PR updates the following changes:
- It check whether SerialNumber is empty or invalid. In both cases, it adds a  newly generated UUID.

### CODE REVIEW

File: pkg/native/serializers/serializer_cdx.go [hunk 1]
```diff
@@ -149,6 +155,13 @@ func (s *CDX) Serialize(bom *sbom.Document, _ *native.SerializeOptions, _ interf
 	return doc, nil
 }
 
+// isValidCycloneDXSerialNumber validates serial id against regex pattern
+func isValidCycloneDXSerialNumber(serial string) bool {
+	pattern := `^urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`
+	matched, _ := regexp.MatchString(pattern, serial)
```
Comment (puerco) [inline pkg/native/serializers/serializer_cdx.go:161]: Define the regexp outside of the function and make sure we compile it only once when needed as dointg it at every function call is expensive.

File: pkg/native/serializers/serializer_cdx.go [hunk 2]
```diff
@@ -45,6 +47,10 @@ func (s *CDX) Serialize(bom *sbom.Document, _ *native.SerializeOptions, _ interf
 
 	doc := cdx.NewBOM()
 	doc.SerialNumber = bom.Metadata.Id
+	if doc.SerialNumber == "" || !isValidCycloneDXSerialNumber(doc.SerialNumber) {
+		doc.SerialNumber = "urn:uuid:" + uuid.New().String()
```
Comment (puerco) [inline pkg/native/serializers/serializer_cdx.go:51]: Lets use here a deterministic algorithm to generate the new serial number. When the protobom document has an ID defined, use an uuid sha1 to generate the uuid, something like:

```golang
uuid.NewSHA1(uuid.MustParse(`5dbcd03c-dd56-4fff-97af-77f89c66eeba`), []byte(protobom id))
```

**Review by puerco — COMMENTED** [review]
Thanks for fixing this @viveksahu26  ! A few initial comments :point_down:

File: pkg/native/serializers/serializer_cdx.go (hunk 2 above)
Comment (puerco) [inline pkg/native/serializers/serializer_cdx.go:51]: Since this is essentially altering the protobom data, we have an option to fail the conversion when the protobom document does not have an Id set. 

See how the SPDX serializer implements it here and make sure we honor it here too:
https://github.com/protobom/protobom/blob/5612e368b95d757401f322ed4939b3957d8d40a0/pkg/native/serializers/serializer_spdx23.go#L88-L95

File: pkg/native/serializers/serializer_cdx.go [hunk 3]
```diff
@@ -17,22 +19,27 @@ import (
...
 	}
 )
 
 func NewCDX(version, encoding string) *CDX {
 	return &CDX{
-		version:  version,
-		encoding: encoding,
+		version:              version,
+		encoding:             encoding,
+		GenerateSerialNumber: false,
```
Comment (puerco) [inline pkg/native/serializers/serializer_cdx.go:42]: Mmh no, sorry... Now that I look at it, the cdx options are not initialized in the serializer. Sorry for the wrong comment in the previous review. 

Let me open a PR to set them up so that you can use them here.

Comment (puerco) [reply pkg/native/serializers/serializer_cdx.go:42]: OK, here: https://github.com/protobom/protobom/pull/327

Feel free to cherry-pick that commit if it helps unblocking you (and I'll close 327).

Comment (puerco) [reply pkg/native/serializers/serializer_cdx.go:42]: Awesome, we merged #327. Just rebase and use the new option to control the serial number generation.

Comment (viveksahu26) [reply pkg/native/serializers/serializer_cdx.go]: done !!

**Review by puerco — APPROVED** [review]
Awesome, thanks @viveksahu26 !
